whisper:
  checkpoint: /mnt/private_cq/whisper_checkpoint

tokenizer:
  simplified_chinese_characters: ./assets/simplified_chinese.txt

trainer:
  seed: 3407

flat_models:
  tiny:
    total: 384
    parts:
      note:
      slur:
      start:
      end:
      hanzi: 200
      pinyin:
      tone:



