# This is the default setting for all dataset, which can be overwritten 
# by the settings with the name of the dataset.
BaseReader: 
  name: 
  identifier:
  summary: 
  category: 
  license: 
  website: 
  path: 
  NONE_TEXT: 'NO'
  SLUR_TEXT: 'SL'
  TEXT_MAX_LENGTH: 120
  AUDIO_MAX_LENGTH: 480000
  SAMPLE_RATE: 16000
  MAX_SECS: 30 # allow 30s = AUDIO_MAX_LENGTH/SAMPLE_RATE
  SEED: 3407
  VERIFY_AUDIO: true # If true, very slow, but only need to generate pickle once. If you trust the dataset is 100% correct, set to false
  DISABLE_TQDM: false # If true, not show finish rate bar in terminal

Openslr33:
  name: AIShell-1
  identifier: SLR33
  summary: Mandarin data, provided by Beijing Shell Shell Technology Co.,Ltd
  category: Speech
  license: Apache License v.2.0
  website: https://www.openslr.org/33
  path: /mnt/private_cq/dataset/Corpus/zipped_file/ft_local/33-Aishell/data_aishell/
  model_size: tiny # one of [tiny, base, small, medium, large-v2], with size [73M, 139M, 462M, 1.5G, 2.9G]

OpenCpop:
  name: OpenCpop
  identifier: OCPOP
  summary: A publicly available high-quality Mandarin singing corpus
  category: Singing
  license: CC BY-NC-ND 4.0
  website: https://wenet.org.cn/opencpop/
  path: /mnt/private_cq/dataset/opencpop

